version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: aprosoft_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: aprosoft
volumes:
  mongo-data: